[workspace]
resolver = "2"
members = [
    "cargo-pgx",
    "pgx",
    "pgx-macros",
    "pgx-pg-sys",
    "pgx-tests",
    "pgx-utils",
    "pgx-examples/aggregate",
    "pgx-examples/arrays",
    "pgx-examples/bad_ideas",
    "pgx-examples/bgworker",
    "pgx-examples/bytea",
    "pgx-examples/custom_types",
    "pgx-examples/custom_sql",
    "pgx-examples/errors",
    "pgx-examples/nostd",
    "pgx-examples/operators",
    "pgx-examples/schemas",
    "pgx-examples/shmem",
    "pgx-examples/spi",
    "pgx-examples/srf",
    "pgx-examples/strings",
    "pgx-examples/triggers",
]

[profile.dev.build-override]
opt-level = 3