[package]
name = "pgx-parent"
version = "0.0.2"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Top-level repo for 'pgx' (not on crates.io)"
homepage = "https://github.com/zombodb/pgx/"
repository = "https://github.com/zombodb/pgx/"

[workspace]
members = [
    ".",
    "cargo-pgx",
    "pgx",
    "pgx-macros",
    "pgx-pg-sys",
    "pgx-tests",
    "pgx-utils",
]

[features]
default = [ ]
pg10 = [ "pgx/pg10", "pgx-pg-sys/pg10" ]
pg11 = [ "pgx/pg11", "pgx-pg-sys/pg11" ]
pg12 = [ "pgx/pg12", "pgx-pg-sys/pg12" ]

[dependencies]
cargo-pgx = { path = "cargo-pgx" }
pgx = { path = "pgx", default-features = false }
pgx-macros = { path = "pgx-macros" }
pgx-pg-sys = { path = "pgx-pg-sys", default-features = false }
pgx-tests = { path = "pgx-tests", default-features = false }
