[package]
name = "pgx-parent"
version = "0.1.19"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Top-level repo for 'pgx' (not on crates.io)"
homepage = "https://github.com/zombodb/pgx/"
repository = "https://github.com/zombodb/pgx/"

[workspace]
members = [
    ".",
    "cargo-pgx",
    "pgx",
    "pgx-macros",
    "pgx-pg-sys",
    "pgx-tests",
    "pgx-utils",
]
exclude = [
    "pgx-examples/arrays",
    "pgx-examples/bad_ideas",
    "pgx-examples/bytea",
    "pgx-examples/custom_types",
    "pgx-examples/errors",
    "pgx-examples/schemas",
    "pgx-examples/shmem",
    "pgx-examples/spi",
    "pgx-examples/srf",
    "pgx-examples/strings",
]

[features]
default = [ ]
pg10 = [ "pgx/pg10", "pgx-pg-sys/pg10", "pgx-tests/pg10" ]
pg11 = [ "pgx/pg11", "pgx-pg-sys/pg11", "pgx-tests/pg11" ]
pg12 = [ "pgx/pg12", "pgx-pg-sys/pg12", "pgx-tests/pg12" ]
pg13 = [ "pgx/pg13", "pgx-pg-sys/pg13", "pgx-tests/pg13" ]
pg_test = [ "pgx-tests/pg_test" ]

[package.metadata.docs.rs]
features = ["pg13"]
no-default-features = true

[dependencies]
cargo-pgx = { path = "cargo-pgx" }
pgx = { path = "pgx", default-features = false }
pgx-macros = { path = "pgx-macros" }
pgx-pg-sys = { path = "pgx-pg-sys", default-features = false }
pgx-tests = { path = "pgx-tests", default-features = false }
