[package]
name = "pgx-tests"
version = "0.1.21"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Test framework for 'pgx'-based Postgres extensions"
homepage = "https://github.com/zombodb/pgx/pg-tests"
repository = "https://github.com/zombodb/pgx/pg-tests"
documentation = "https://docs.rs/pgx-tests"
readme = "README.md"

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
default = [ ]
pg10 = [ "pgx/pg10" ]
pg11 = [ "pgx/pg11" ]
pg12 = [ "pgx/pg12" ]
pg13 = [ "pgx/pg13" ]
pg_test = [ ]

[package.metadata.docs.rs]
features = ["pg13"]
no-default-features = true

[dependencies]
colored = "2.0.0"
lazy_static = "1.4.0"
libc = "0.2.94"
pgx = { path = "../pgx", default-features = false, version= "0.1.20"}
pgx-macros = { path = "../pgx-macros", version= "0.1.20"}
pgx-utils = { path = "../pgx-utils", version= "0.1.20"}
postgres = "0.19.1"
regex = "1.5.4"
serde = "1.0.125"
serde_json = "1.0.64"
shutdown_hooks = "0.1.0"
time = "0.2.26"
