[package]
name = "pgx-tests"
version = "0.4.4"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
license = "MIT"
description = "Test framework for 'pgx'-based Postgres extensions"
homepage = "https://github.com/zombodb/pgx"
repository = "https://github.com/zombodb/pgx"
documentation = "https://docs.rs/pgx-tests"
readme = "README.md"
edition = "2021"

[lib]
crate-type = [ "cdylib", "lib" ]

[features]
default = [ ]
pg10 = [ "pgx/pg10" ]
pg11 = [ "pgx/pg11" ]
pg12 = [ "pgx/pg12" ]
pg13 = [ "pgx/pg13" ]
pg14 = [ "pgx/pg14" ]
pg_test = [ ]

[package.metadata.docs.rs]
features = ["pg14"]
no-default-features = true
targets = ["x86_64-unknown-linux-gnu"]
# Enable `#[cfg(docsrs)]` (https://docs.rs/about/builds#cross-compiling)
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
owo-colors = "3.4.0"
once_cell = "1.10.0"
libc = "0.2.125"
pgx = { path = "../pgx", default-features = false, version= "0.4.4" }
pgx-macros = { path = "../pgx-macros", version= "0.4.4" }
pgx-utils = { path = "../pgx-utils", version= "0.4.4" }
postgres = "0.19.3"
regex = "1.5.5"
serde = "1.0.137"
serde_json = "1.0.80"
shutdown_hooks = "0.1.0"
time = "0.3.9"
eyre = "0.6.8"
