[package]
name = "pgrx-sql-entity-graph"
version = "0.9.4"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
license = "MIT"
description = "Sql Entity Graph for `pgrx`"
homepage = "https://github.com/tcdi/pgrx"
repository = "https://github.com/tcdi/pgrx"
documentation = "https://docs.rs/pgrx-sql-entity-graph"
readme = "README.md"
edition = "2021"

[features]
syntax-highlighting = ["dep:syntect", "dep:owo-colors", "dep:atty"]
no-schema-generation = []

[dependencies]
convert_case = "0.6.0"
eyre = "0.6.8"
petgraph = "0.6.3"
proc-macro2 = { version = "1.0.60", features = [ "span-locations" ] }
quote = "1.0.28"
syn = { version = "1.0.109", features = [ "extra-traits", "full", "fold", "parsing" ] }
unescape = "0.1.0"

# colorized sql output
atty = { version = "0.2.14", optional = true }
owo-colors = { version = "3.5.0", optional = true }
syntect = { version = "5.0.0", default-features = false, features = ["default-fancy"], optional = true }
