[package]
name = "pgx-pg-config"
version = "0.5.0-beta.0"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
license = "MIT"
description = "A Postgres pg_config wrapper for 'pgx'"
homepage = "https://github.com/zombodb/pgx"
repository = "https://github.com/zombodb/pgx"
#documentation = "https://docs.rs/pgx-utils"
readme = "README.md"
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
eyre = "0.6.8"
owo-colors = "3.4.0"
serde = { version = "1.0.137", features = [ "derive" ] }
serde_derive = "1.0.137"
serde_json = "1.0.81"
toml = "0.5.9"
tracing = "0.1.34"
tracing-error = "0.2.0"
url = "2.2.2"
