name: cargo-pgx-init

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  cargo-pgx-init:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v2

    - name: cargo version
      run: cargo --version

    # Ubuntu system dependencies for Postgres
    - name: remove old postgres
      run: sudo apt remove -y postgres*

    # Update apt
    - name: update apt
      run: |
        sudo apt-get update -y -qq --fix-missing
        sudo apt-get install -y wget gnupg
        sudo bash -c 'echo deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main >> /etc/apt/sources.list.d/pgdg.list'
        sudo apt update

    # Install Postgres build dependencies
    - name: install postgres build dependencies
      run: sudo apt-get install -y clang-10 llvm-10 clang gcc make build-essential libz-dev zlib1g-dev strace libssl-dev pkg-config

    # install cargo-pgx
    - name: install cargo-pgx
      run: cargo install --path cargo-pgx/ --debug

    # initialize pgx with all PG versions it supports
    - name: cargo pgx init
      run: cargo pgx init

    # create new sample extension
    - name: create new sample extension
      run: cd /tmp/ && cargo pgx new sample

    # hack Cargo.toml to use this version of pgx from github
    - name: hack Cargo.toml
      run: |
       echo '[patch.crates-io]' >> /tmp/sample/Cargo.toml
       echo pgx = '{' git = '"'https://github.com/zombodb/pgx'"', package = '"'pgx'"', rev = '"'${GITHUB_SHA}'"' '}' >> /tmp/sample/Cargo.toml
       echo pgx-macros = '{' git = '"'https://github.com/zombodb/pgx'"', package = '"'pgx-macros'"', rev = '"'${GITHUB_SHA}'"' '}' >> /tmp/sample/Cargo.toml
       echo pgx-tests = '{' git = '"'https://github.com/zombodb/pgx'"', package = '"'pgx-tests'"', rev = '"'${GITHUB_SHA}'"' '}' >> /tmp/sample/Cargo.toml

# test that sample extension on all 4 Postgres'
    - name: test sample on pg10
      run: cd /tmp/sample && cargo pgx test pg10
    - name: test sample on pg11
      run: cd /tmp/sample && cargo pgx test pg11
    - name: test sample on pg12
      run: cd /tmp/sample && cargo pgx test pg12
    - name: test sample on pg13
      run: cd /tmp/sample && cargo pgx test pg13
    - name: test sample on pg14
      run: cd /tmp/sample && cargo pgx test pg14

