name: test examples

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  examples:
    name: ${{ matrix.examples }} example for pg${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        version: [10, 11, 12, 13]
        os: ["ubuntu-latest"]
        examples: ["arrays", "bad_ideas", "bgworker", "bytea", "custom_types", "errors", "operators", "schemas", "shmem", "spi", "srf", "strings"]

    steps:
    - uses: actions/checkout@v2

    - name: cargo version
      run: cargo --version

    # Ubuntu system dependencies for Postgres
    - name: remove old postgres
      run: sudo apt remove -y postgres*

    # Update apt
    - name: update apt
      run: sudo apt-get update -y -qq --fix-missing

    # Install Postgres
    - name: install postgres
      run: sudo apt-get install -y clang-10 llvm-10 clang gcc make build-essential libz-dev zlib1g-dev strace libssl-dev pkg-config postgresql-${{ matrix.version }} postgresql-server-dev-${{ matrix.version }}
    - name: hack Postgres permissions
      run: sudo chmod a+rwx `pg_config --pkglibdir` `pg_config --sharedir`/extension /var/run/postgresql/

    # install cargo-pgx
    - name: install cargo-pgx
      run: cargo install --path cargo-pgx/ --debug

    # initialize pgx for this PG version
    - name: cargo pgx init
      run: cargo pgx init --pg${{ matrix.version }}=`which pg_config`

    - name: config.toml
      run: cat ~/.pgx/config.toml

    - name: pg_config version
      run: pg_config --version

    # make sure the examples build too and build them in the matrix
    - name: ${{ matrix.examples }} example on pg${{ matrix.version }}
      run: cd pgx-examples/${{ matrix.examples }} && cargo pgx test pg${{ matrix.version }}
